---@class dracula.palette
---@field base0? string
---@field base01? string
---@field base02? string
---@field base03? string
---@field base04? string
---@field cyan? string
---@field diag_error? string
---@field diag_hint? string
---@field diag_info? string
---@field diag_ok? string
---@field diag_warning? string
---@field git_added? string
---@field git_modified? string
---@field git_removed? string
---@field green? string
---@field inlay_hint? string
---@field orange? string
---@field pink? string
---@field purple? string
---@field red? string
---@field shade_add? string
---@field shade_change? string
---@field shade_cyan? string
---@field shade_error? string
---@field shade_green? string
---@field shade_hint? string
---@field shade_info? string
---@field shade_ok? string
---@field shade_orange? string
---@field shade_pink? string
---@field shade_purple? string
---@field shade_red? string
---@field shade_warning? string
---@field shade_yellow? string
---@field yellow? string
return {
  base0 = '#F8F8F2',
  base01 = '#7970a9',
  base02 = '#454158',
  base03 = '#22212c',
  base04 = '#11111b',
  cyan = '#80ffea',
  diag_error = '#ff9580',
  diag_hint = '#80ffea',
  diag_info = '#80ffea',
  diag_ok = '#8aff80',
  diag_warning = '#ffca80',
  git_added = '#8aff80',
  git_modified = '#ffca80',
  git_removed = '#ff9580',
  green = '#50FA7A',
  inlay_hint = '#282a36',
  orange = '#ffca80',
  pink = '#ff80bf',
  purple = '#9580ff',
  red = '#ff9580',
  shade_add = '#2E4940',
  shade_change = '#483F3E',
  shade_cyan = '#374754',
  shade_error = '#48303B',
  shade_green = '#2E4940',
  shade_hint = '#374754',
  shade_info = '#374754',
  shade_ok = '#2E4940',
  shade_orange = '#483F3E',
  shade_pink = '#5E3E5A',
  shade_purple = '#3E3A53',
  shade_red = '#48303B',
  shade_warning = '#483F3E',
  shade_yellow = '#464943',
  yellow = '#ffff80',
}
